# Generated by Django 2.2 on 2020-04-03 07:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=264)),
                ('Type', models.CharField(blank=True, choices=[('2 Wheeler', '2 Wheeler'), ('4 Wheeler', '4 Wheeler')], max_length=264)),
                ('image', models.ImageField(upload_to='img')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('customerentry_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
