# Generated by Django 2.2 on 2020-04-03 10:20

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('dbconnect_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='content',
            field=djrichtextfield.models.RichTextField(default='gbuguy uuhiuhuihihih uguy!'),
        ),
    ]
