# Generated by Django 2.2 on 2020-04-03 11:04

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbconnect_app', '0002_vehicle_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
